### PR TITLE
Support playing back OPUS audio

### PR DESCRIPTION
**Pull request by marty1885**
This PR adds the following capability to Lagrange. 

* Ability to decode OPUS audio using `libopusfile`
* Detect OPUS when capsule replies `audio/ogg` as currently Lagrange assumes OGG uses Vorbis

### CODE REVIEW

**Comment by marty1885** [comment]
Actually hold on. It seems to not fully load the audio when only partial data is provided at first. Weird.

**Comment by skyjake** [comment]
All right. Let me know when/if you figure out the cause. Otherwise, at a glance at least, this looks good to be merged to the upcoming v1.18.

I can't promise I'll include this in every prebuilt binary, though, due to the hassles with adding new dependencies to the distribution.

**Comment by marty1885** [comment]
@skyjake Can you review my code again? I found the issue. Turns out libopusfile doesn't really do streaming even though the API allows. It will attempt to determine amount of audio in the buffer during initializing. Then only decode up to that amount.

I ended up re-opening the audio upon new data is available. Then seek (this is fast due to OGG containing sample counter in the file) back up to the previous progress. If this is a performance concert, I can make it only start decoding when the  OPUS file is fully downloaded.

**Comment by marty1885** [comment]
@skyjake ping. Can we get this merged?

**Comment by skyjake** [comment]
It is now in the dev branch and the branch has been bumped to v1.18.

Releasing v1.18 may take a few months as I haven't really started working on it yet.

**Pull request merged**
