### PR TITLE
app: Raise windows when opening new tabs via IPC

### PR DESCRIPTION
**Pull request by alyssarosenzweig**
When Lagrange is opened via a terminal -- or more importantly, when
opened as a MIME handler for gemini:// links in other applications --
users expect Lagrange to take focus. However, if Lagrange is already
open and the request is piped over IPC, this fails. In theory this
should be as simple as adding a SDL_RaiseWindow() in the right place. In
practice there's a chain of race conditions that make the obvious
solution fail in a non-obvious way.

Signed-off-by: Alyssa Rosenzweig <alyssa@rosenzweig.io>

### CODE REVIEW

**Comment by alyssarosenzweig** [comment]
Note: I'm nt familiar enough with the SDL event loop to know if accessing window from here is safe. If it isn't, we need some other way to block. [That is - the bug this fixes is very real. Whether this is the correct fix is unclear.]

**Comment by skyjake** [comment]
Thanks for working this out. I was thinking of implementing window raising at some point but wasn't even aware of this focus-stealing prevention trickery.  However, the IPC signal may be handled in any thread, so `postCommand_App` might not be called in the main thread and I'm pretty sure SDL wants windows accessed only from there.

So what should occur is that the CLI requests a raise and blocks in `communicate_Ipc_` until the window actually has been raised. I think the simplest way to do this is to add a parameter to the "ipc.signal" command (it gets always appended at the end in `write_Ipc`). The recipient executes this command when the previous actions have been done, and it's guaranteed to run on the event loop in the main thread. So something like "ipc.signal arg:12345 raise:1".

**Comment by alyssarosenzweig** [comment]
>    However, the IPC signal may be handled in any thread, so
>    postCommand_App might not be called in the main thread and I'm pretty sure
>    SDL wants windows accessed only from there.

I was afraid there'd be something like that. This was mostly a drive-by
so if you were planning on finishing this anyway, please don't block on
me. (If not, I'm not sure when I'll have time to do Gemini patches
next.)

The situation on Linux/Wayland is more dire, as pointed on #sdl on IRC.
There's no standardized protocol for raising whatsoever. GNOME Wayland
has a special vendored protocol accessible via GTK, but short of adding
a GTK backend to SDL I'm not sure how to make use of that. I'm not sure
if KDE has an equivalent protocol, but the one I saw is decidedly GNOME
specific. It's a shame there isn't a 'cleaner' way of expressing this
pattern.

**Comment by skyjake** [comment]
Sure, I can make the needed changes and merge this, no worries.

**Comment by skyjake** [comment]
f033188b8103135b4e4ce1746bfc26a527323ba8 includes the suggested changes.

**Pull request closed without merging**
