### PR TITLE
Add a Debian release packaging workflow using GitHub CI

### PR DESCRIPTION
**Pull request by epilys**
Hello, wanted to checkout lagrange on my laptop and took the chance to learn github's CI a little bit.

### CODE REVIEW

**Comment by skyjake** [comment]
Thanks! Are you also volunteering to maintain this Debian package metadata in the future, or do you want me to fill in the blanks so to speak? Either way is fine with me since this is for a CI build / unofficial package.

**Comment by epilys** [comment]
The package metadata is not important for an unofficial package. The important thing to change is the release version which I have described in the second commit message. Should be easy to maintain unless the build process changes.

**Comment by skyjake** [comment]
I haven't used GitHub's CI stuff myself so I'm unclear on the details here, sorry. If the Debian package is only for CI purposes, why does it need a proper version? Couldn't it just be fixed to "0.0.0-ci" or something, thus removing the need for any manual actions?

**Comment by epilys** [comment]
The debian package tooling fails to build without a version, and if you have it 0.0.0-ci permanently you would not be able to update packages (you'd have to uninstall and reinstall manually). The proper way should be to do this automatically on a tag release, I guess.

**Comment by skyjake** [comment]
I've given this some more thought and here's my issue with the PR:

> Builds can be triggered manually (`workflow_dispatch`) and by pushing a tagged release (`v*.*.*`)

CI builds should be completely automated and occur after every commit to be effective. So this workflow is not CI, but instead it is a semi-automated Debian package builder for distribution of binary .debs, which I believe you mean to have installed and updated automatically on one's system? Since those .debs originate from the Lagrange repo, they should be considered "official" and thus have all the correct metadata. Please correct me if I've misunderstood something.

I suggest taking one or both of these actions:
* Make an after-every-commit CI workflow that just ensures everything builds fine on Ubuntu/Debian via the deb build tools, or just by doing a plain CMake build. The assumption is that the artifact .debs will not be systematically tested, unless there are automated tests to run (which currently there aren't). 
* Make a fully automated release tag workflow that generates .deb packages for Ubuntu/Debian so that these can be provided as the official binaries for those operating systems.

I can fix up the metadata myself, but it would be great if you can still work on the "fully automated" part. It's also fine if you're not interested; I can work on this at some suitable point in the future. 🙂

**Comment by epilys** [comment]
> CI builds should be completely automated and occur after every commit to be effective. So this workflow is not CI

It uses Github CI to build packages out of **releases**. You can add a separate Github action to build/test after every commit, but that's a separate thing.

> Make a fully automated release tag workflow that generates .deb packages for Ubuntu/Debian so that these can be provided as the official binaries for those operating systems.

The second commit adds this, except for the full automation part. The only non-automated part is the fact that you have to write down the version in the github action file and in the `debian/` metadata

While obviously all this is _necessary_ improvements to this PR I published it because you might want to have available binaries for download right now. If you see [the results of the build in my fork ](https://github.com/epilys/lagrange/actions/runs/326533677) you can download the artifacts and then upload them on the Github Releases page by editing a release.

> s, which I believe you mean to have installed and updated automatically on one's system? Since those .debs originate from the Lagrange repo, they should be considered "official" and thus have all the correct metadata. Please correct me if I've misunderstood something.

You need to set up an APT repository server for that, that users add to their APT config files. With plain *.deb files the user downloads them from your repository releases and/or site and manually runs `dpkg -i lagrange_*****.deb` which installs the package archive.

**Comment by skyjake** [comment]
Thanks for the explanation, I think we're on the same page now. 👍

So to summarize, I'll need to fix up the package metadata before I can provide these .debs to users, but otherwise this should be quite useful as part of the release process. I'll get this merged when I have a suitable moment to work on it.

**Pull request merged**
